name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Pylint Quality Check"] # Doit correspondre exactement au 'name' du premier fichier
    types:
      - completed
    #branches:
    #  - main

jobs:
  on-success:
    runs-on: ubuntu-latest
    # CRUCIAL : On vérifie que le workflow Pylint s'est terminé par une RÉUSSITE (success)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Execute remote deploy script via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          echo "Connexion SSH réussie. Déclenchement du script de déploiement..."
          sudo /appli/genealogie/app/deploy.sh